name: Build

on:
  push:
    branches:
      - main
      - "1.x.x"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install VCPKG Packages
        run: |
          vcpkg install cpp-httplib:x86-windows
          vcpkg install nlohmann-json:x86-windows
          vcpkg integrate install

      - name: Build
        working-directory: ${{ github.workspace }}
        run: msbuild "Taskbar Lyrics.sln" -p:Configuration=Release -p:Platform="x86"

      - name: Package Plugin
        run: |
          Compress-Archive -Path dist\* -DestinationPath Taskbar-Lyric-dev.plugin -Force

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Taskbar-Lyric-dev
          path: Taskbar-Lyric-dev.plugin

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Taskbar-Lyric-dev

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          target-folder: dist
          folder: dist
